[build]
  command = "bun run build"
  publish = "out" # because output is 'export', Next.js will generate 'out' folder

[build.environment]
  # No need to set NETLIFY_NEXT_PLUGIN_SKIP anymore
  NODE_VERSION = "18" # example, optional
  CLOUDINARY_CLOUD_NAME = "rohitkrsah"
  CLOUDINARY_API_KEY = "225697353752836"
  CLOUDINARY_API_SECRET = "8qyNVb_MFlOqwYmlUeL4tvIe1m0"

[images]
  remote_images = [
    "https://source.unsplash.com/.*",
    "https://images.unsplash.com/.*",
    "https://ext.same-assets.com/.*",
    "https://ugc.same-assets.com/.*",
    "https://res.cloudinary.com/rohitkrsah/.*"
  ]

# No need for any plugin block when using static export

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
